package com.ihridoydas.simpleapp.util.responsiveUI.component.card

import androidx.compose.ui.graphics.Color

object Data {

    val cards = listOf(
        CardData(
            "G1",
            Color(0xFFFF5858),
            Color(0xFFFFC793)
        ) {},
        CardData(
            "G2",
            Color(0xFF3BFF95),
            Color(0xFF00A3FF)
        ){},
        CardData(
            "G3",
            Color(0xFFA89BBB),
            Color(0xFF363062)
        ){},
        CardData(
            "G4",
            Color(0xFFAAC32C),
            Color(0xFFFCF9C6)
        ){},
        CardData(
            "G5",
            Color(0xFFFF7700),
            Color(0xFFF4F269)
        ){},
        CardData(
            "G6",
            Color(0xFFFF00F5),
            Color(0xFF7700FF)
        ){},
        CardData(
            "G7",
            Color(0xFFAF2CFF),
            Color(0xFF3CFFDC)
        ){},
        CardData(
            "G8",
            Color(0xFFEBFF00),
            Color(0xFFFF007A)
        ){},
        CardData(
            "G9",
            Color(0xFFFF1D1D),
            Color(0xFFE000D7)
        ){},
        CardData(
            "G10",
            Color(0xFF00FFC2),
            Color(0xFFECFFA1)
        ){},
        CardData(
            "G11",
            Color(0xFFFF5858),
            Color(0xFFFFC793)
        ){},
        CardData(
            "G12",
            Color(0xFF3BFF95),
            Color(0xFF00A3FF)
        ){},
        CardData(
            "G13",
            Color(0xFFA89BBB),
            Color(0xFF363062)
        ){},
        CardData(
            "G14",
            Color(0xFFAAC32C),
            Color(0xFFFCF9C6)
        ){},
        CardData(
            "G15",
            Color(0xFFFF7700),
            Color(0xFFF4F269)
        ){},
        CardData(
            "G16",
            Color(0xFFFF00F5),
            Color(0xFF7700FF)
        ){},
        CardData(
            "G17",
            Color(0xFFAF2CFF),
            Color(0xFF3CFFDC)
        ){},
        CardData(
            "G18",
            Color(0xFFEBFF00),
            Color(0xFFFF007A)
        ){},
        CardData(
            "G19",
            Color(0xFFFF1D1D),
            Color(0xFFE000D7)
        ){},
        CardData(
            "G20",
            Color(0xFF00FFC2),
            Color(0xFFECFFA1)
        ){},
    )
}